# Use this docker-compose file to build RetroSpy for test purposes.

version: '3.7'
services:
  cdkey:
    build:
      context: ../
      dockerfile: ./src/Servers/CDKey/Dockerfile
    image: gameprogressive/cdkey
    ports:
    - "29910:29910"
    - "29910:29910/udp"
    stdin_open: true
    tty: true

  chat:
    build:
      context: ../
      dockerfile: ./src/Servers/Chat/Dockerfile
    image: gameprogressive/chat
    ports:
    - "6667:6667"
    stdin_open: true
    tty: true

  nn:
    build:
      context: ../
      dockerfile: ./src/Servers/NATNegotiation/Dockerfile
    image: gameprogressive/nn
    ports:
    - "27901:27901"
    - "27901:27901/udp"
    stdin_open: true
    tty: true

  pcm:
    build:
      context: ../
      dockerfile: ./src/Servers/PresenceConnectionManager/Dockerfile
    image: gameprogressive/pcm
    ports:
    - "29900:29900"
    stdin_open: true
    tty: true

  psp:
    build:
      context: ../
      dockerfile: ./src/Servers/PresenceSearchPlayer/Dockerfile
    image: gameprogressive/psp
    ports:
    - "29901:29901"
    stdin_open: true
    tty: true

  qr:
    build:
      context: ../
      dockerfile: ./src/Servers/QueryReport/Dockerfile
    image: gameprogressive/qr
    ports:
    - "27900:27900"
    - "27900:27900/udp"
    stdin_open: true
    tty: true

  sb:
    build:
      context: ../
      dockerfile: ./src/Servers/ServerBrowser/Dockerfile
    image: gameprogressive/sb
    ports:
    - "28910:28910"
    stdin_open: true
    tty: true

  gs:
    build:
      context: ../
      dockerfile: ./src/Servers/GameStatus/Dockerfile
    image: gameprogressive/gs
    ports:
    - "29920:29920"
    stdin_open: true
    tty: true

  ws:
    build:
      context: ../
      dockerfile: ./src/Servers/WebServices/Dockerfile
    image: gameprogressive/ws
    ports:
    - "80:80"
    - "443:443"
