name: CI

on:
  push:
    branches-ignore:
      - master
      - candidate
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Test on .NET v${{ matrix.dotnet_version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['5.0']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET ${{ matrix.dotnet_version }}
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet_version }}
      - name: Building project
        run: dotnet build
