name: CI

on:
  push:
    branches:
      - master
      - candidate
      - develop
  pull_request:

jobs:
  unispy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore