name: CD - PCM

on:
  push:
    paths:
      - 'src/Servers/PresenceConnectionManager/**'
    branches:
      - master
      - candidate

jobs:
  build:
    name: Test on .NET v${{ matrix.dotnet_version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: ['5.0.100']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET ${{ matrix.dotnet_version }}
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet_version }}
      - name: Building project
        run: dotnet build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy PCM to staging
        if: github.ref == 'refs/heads/candidate'
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: gameprogressive/pcm
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          tagging: true
          dockerfile: ./src/Servers/PresenceConnectionManager/Dockerfile
      - name: Deploy PCM to production
        if: github.ref == 'refs/heads/master'
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: gameprogressive/pcm
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          tagging: true
          dockerfile: ./src/Servers/PresenceConnectionManager/Dockerfile